apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: serveimages
    tier: frontend
spec:
  containers:
  - name: myapp-container
    image: nginx:1.7.9
    ports:
    - containerPort: 80